const series=["J7","J6","J6P","J6L","JH6","JK6","J6F","J5","虎6G","领途","鹰途","鹰阵","V卡"];
const fallbackIntents=[{id:"all",name:"智能问答",scene:""},{id:"vin",name:"VIN查询",scene:""},{id:"fault",name:"故障码",scene:"修"},{id:"symptom",name:"症状查询",scene:"修"},{id:"usage",name:"用车知识",scene:"用"},{id:"maintenance",name:"保养知识",scene:"养"},{id:"warranty",name:"保用知识",scene:"保"}];
const taskLabels={vin:"VIN车辆信息",fault_code:"故障码诊断",symptom_diagnosis:"症状诊断",usage:"用车知识",maintenance:"保养知识",warranty:"保用知识",service_technical:"服务技术",drawing:"图纸资料",claim_case:"索赔案例",general:"综合知识"};
const intentTaskTypes={vin:"vin",fault:"fault_code",symptom:"symptom_diagnosis",usage:"usage",maintenance:"maintenance",warranty:"warranty"};
const state={conversationId:null,last:null,image:null,diagnosticPrompt:"",intent:"all",intents:fallbackIntents};
const $=id=>document.getElementById(id);
const esc=value=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[char]));
series.forEach(value=>{const option=document.createElement("option");option.value=value;option.textContent=value;$("vehicleSeries").append(option)});

async function getJson(url,options){const response=await fetch(url,options);const data=await response.json();if(!response.ok)throw new Error(data.error||"请求失败");return data}
async function getStream(url,options,handlers={}){const response=await fetch(url,options);if(!response.ok)throw new Error(`请求失败（${response.status}）`);const reader=response.body.getReader();const decoder=new TextDecoder();let buffer="";let result=null;while(true){const{done,value}=await reader.read();buffer+=decoder.decode(value||new Uint8Array(),{stream:!done});const lines=buffer.split("\n");buffer=lines.pop()||"";for(const line of lines){if(!line.trim())continue;const event=JSON.parse(line);if(event.type==="status")handlers.onStatus?.(event);if(event.type==="meta")handlers.onMeta?.(event);if(event.type==="delta")handlers.onDelta?.(event);if(event.type==="mode_fallback")handlers.onFallback?.(event);if(event.type==="error")throw new Error(event.error||"流式回答失败");if(event.type==="done")result=event.data}if(done)break}if(!result)throw new Error("流式响应未完成");return result}
function updateClock(){const now=new Date();$("clock").textContent=`${String(now.getHours()).padStart(2,"0")}:${String(now.getMinutes()).padStart(2,"0")}`}
async function loadStatus(){try{const data=await getJson("/api/health");const agent=data.agent||{};const qdrant=data.retrieval?.qdrant||{};const activeMode=agent.modes?.[$("answerMode").value]||{};$("agentStatus").textContent=agent.configured?`${activeMode.label||agent.provider_name||"火山方舟"} · ${activeMode.model||agent.model}`:"知识库在线 · 智能体待配置";$("retrievalStatus").textContent=qdrant.ready?`${qdrant.model||"向量模型"} · ${Number(qdrant.points||0).toLocaleString("zh-CN")} 条知识向量`:"向量检索尚未就绪";$("retrievalStatus").classList.toggle("online",Boolean(qdrant.ready))}catch{$("agentStatus").textContent="知识库暂时无法连接";$("retrievalStatus").textContent="请检查新版向量服务"}}
let scrollQueued=false;function scrollBottom(){if(scrollQueued)return;scrollQueued=true;requestAnimationFrame(()=>{scrollQueued=false;window.scrollTo(0,document.body.scrollHeight)})}

function addUser(text){const row=document.createElement("article");row.className="bubble-row user";row.innerHTML=`<div class="bubble">${esc(text)}</div>`;$("conversation").append(row);scrollBottom()}
function addThinking(){const row=document.createElement("article");row.className="bubble-row assistant thinking";row.id="thinking";row.innerHTML='<div class="avatar">智</div><div class="bubble">正在检索企业资料并分析<span class="thinking-dots"></span></div>';$("conversation").append(row);scrollBottom()}
function updateThinking(text,streaming=false){const bubble=$("thinking")?.querySelector(".bubble");if(!bubble)return;bubble.textContent=text;if(!streaming)bubble.insertAdjacentHTML("beforeend",'<span class="thinking-dots"></span>');scrollBottom()}
function createThinkingRenderer(){let received="";let shown="";let stopped=false;const tick=()=>{if(stopped)return;const pending=received.length-shown.length;if(pending<=0)return;const take=pending<=12?pending:Math.min(12,Math.max(3,Math.ceil(pending/4)));shown=received.slice(0,shown.length+take);updateThinking(shown,true)};const timer=setInterval(tick,32);return{get hasDelta(){return received.length>0},status(text){if(!received)updateThinking(text)},push(text){if(text)received+=text},async finish(){if(stopped)return;clearInterval(timer);const deadline=Date.now()+500;while(shown.length<received.length&&Date.now()<deadline){const pending=received.length-shown.length;shown=received.slice(0,shown.length+Math.min(24,Math.max(4,Math.ceil(pending/5))));updateThinking(shown,true);await new Promise(resolve=>setTimeout(resolve,20))}shown=received;if(shown)updateThinking(shown,true);stopped=true},stop(){if(stopped)return;stopped=true;clearInterval(timer)}}}
function removeThinking(){$("thinking")?.remove()}
function formatAnswer(data){const parts=[data.answer];if(data.solution_steps?.length)parts.push(`\n处理步骤：\n${data.solution_steps.map((item,index)=>`${index+1}. ${item}`).join("\n")}`);if(data.safety_notice)parts.push(`\n安全提示：${data.safety_notice}`);return parts.filter(Boolean).join("\n")}
function richAnswer(data){return esc(formatAnswer(data)).replace(/[【\[]资料\s*(\d+)[】\]]/g,'<button type="button" class="inline-citation" data-source="$1">【资料$1】</button>')}
function isContextualReply(value){return /^(是|是的|对|有|有的|没有|否|不是|亮了|点亮了|没亮|未点亮|正常|不正常|能|不能|可以|不可以|不确定|不知道|偶发|一直)$/.test(String(value||"").replace(/[\s，。！？,.!?]/g,""))}
function retrievalBadge(data){const retrieval=data.retrieval||{};const scope=retrieval.scope||"professional";const exact=Number(retrieval.exact_fault_match_count||0);const task=retrieval.task_type||(scope==="general"?"general":"");if(!task&&!retrieval.method)return"";const route=scope==="general"?"通用模型回答":exact?"故障码精确索引":"分类混合检索";const count=Number(retrieval.source_count||0);const elapsed=Math.round(Number(data.timing?.retrieval_ms||0));return `<div class="retrieval-trace"><span>${esc(taskLabels[task]||"智能分类")}</span><span>${route}</span>${exact?`<span>精确命中 ${exact} 条</span>`:count?`<span>采用 ${count} 条资料</span>`:""}${elapsed?`<span>${elapsed}ms</span>`:""}</div>`}

function addAssistant(data,question){const row=document.createElement("article");row.className="bubble-row assistant";const diagnosis=data.diagnosis?.enabled?`<section class="diagnosis-card ${data.diagnosis.safety_level==="高"?"high-risk":""}"><b>${esc(data.diagnosis.title)}</b><small>证据：${esc(data.diagnosis.evidence_status)} · 安全等级：${esc(data.diagnosis.safety_level)}</small>${data.diagnosis.context_applied?'<em class="context-badge">已结合上一轮回答继续分析</em>':""}${(data.diagnosis.checklist||[]).map((item,index)=>`<p>${index+1}. ${esc(item)}</p>`).join("")}${data.diagnosis.pending_question?`<div class="diagnosis-prompt"><small>下一步请确认</small>${esc(data.diagnosis.pending_question)}</div>`:""}<div class="diagnosis-options">${(data.diagnosis.reply_options||[]).map(item=>`<button type="button" data-answer="${esc(item)}" data-prompt="${esc(data.diagnosis.pending_question)}">${esc(item)}</button>`).join("")}</div></section>`:"";const related=(data.related_questions||[]).map(item=>`<button type="button">${esc(item)}</button>`).join("");const references=(data.reference_materials||data.sources||[]).slice(0,10).map((item,index)=>`<a id="mini-source-${index+1}" href="${esc(item.document_url||item.file_url)}" target="_blank"><b>资料${index+1} · ${esc(item.file_name)}</b><span>${esc(item.source_locator)}</span><p>${esc(String(item.excerpt||"").slice(0,600))}</p></a>`).join("");const error=data.agent&&!data.agent.ok?`<div class="agent-error">${esc(data.agent.error||"智能体调用失败，当前为检索摘要")}</div>`:"";row.innerHTML=`<div class="avatar">智</div><div class="bubble">${error}${retrievalBadge(data)}<div class="rich-answer">${richAnswer(data)}</div>${diagnosis}${related?`<div class="related">${related}</div>`:""}${references?`<details class="source-fold"><summary>引用来源（${(data.reference_materials||data.sources||[]).slice(0,10).length}）</summary><div class="source-list">${references}</div></details>`:""}<div class="feedback"><button type="button" data-rating="up">👍 有帮助</button><button type="button" data-rating="down">👎 需纠偏</button></div></div>`;row.querySelectorAll(".inline-citation").forEach(button=>button.addEventListener("click",()=>{const details=row.querySelector(".source-fold");if(details)details.open=true;document.getElementById(`mini-source-${button.dataset.source}`)?.scrollIntoView({behavior:"smooth",block:"center"})}));row.querySelectorAll(".diagnosis-options button").forEach(button=>button.addEventListener("click",()=>ask(button.dataset.answer,button.dataset.prompt)));row.querySelectorAll(".related button").forEach(button=>button.addEventListener("click",()=>ask(button.textContent)));row.querySelectorAll(".feedback button").forEach(button=>button.addEventListener("click",()=>saveFeedback(button.dataset.rating,data,question,row)));$("conversation").append(row);scrollBottom()}

async function ask(question,explicitPrompt=""){if(!question)return;if(state.intent==="vin"){addUser(question);try{const data=await getJson(`/api/vin?q=${encodeURIComponent(question)}`);addAssistant({answer:data.message,sources:[],reference_materials:[]},question)}catch(error){addAssistant({answer:error.message,sources:[],reference_materials:[]},question)}return}const replyTo=explicitPrompt||(isContextualReply(question)?state.diagnosticPrompt:"");const image=state.image;state.image=null;$("imageStatus").hidden=true;$("quickSection").hidden=true;addUser(question+(replyTo?`\n（回答：${replyTo}）`:"")+(image?"\n[已附图片并完成文字识别]":""));addThinking();$("sendButton").disabled=true;const renderer=createThinkingRenderer();try{const payload={question,intent:state.intent,task_type:intentTaskTypes[state.intent]||"",conversation_id:state.conversationId,vehicle_series:$("vehicleSeries").value,scene:$("scene").value,image_ocr_text:image?.text||"",image_name:image?.name||"",reply_to_question:replyTo,use_agent:true,answer_mode:$("answerMode").value,include_images:false};const data=await getStream("/api/search/stream",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)},{onStatus:event=>renderer.status(event.text),onMeta:event=>renderer.status(event.text),onFallback:event=>{if(event.answer_mode==="fast"||event.answer_mode==="deep")$("answerMode").value=event.answer_mode;renderer.status(event.text)},onDelta:event=>renderer.push(event.text||"")});await renderer.finish();if(data.answer_mode==="fast"||data.answer_mode==="deep")$("answerMode").value=data.answer_mode;state.conversationId=data.conversation_id;state.diagnosticPrompt=data.diagnosis?.pending_question||"";state.last={question,data};removeThinking();addAssistant(data,question);loadHistory()}catch(error){renderer.stop();removeThinking();addAssistant({answer:`问答失败：${error.message}`,sources:[],reference_materials:[],related_questions:[],agent:{ok:false,error:error.message}},question)}finally{renderer.stop();$("sendButton").disabled=false}}
async function recognizeImage(file){if(!file)return;$("imageStatus").hidden=false;$("imageStatus").textContent="正在本地识别图片文字…";try{const dataUrl=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file)});const data=await getJson("/api/image/recognize",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({image_base64:dataUrl,file_name:file.name})});state.image={name:file.name,text:data.text};$("imageStatus").textContent=`已识别 ${data.line_count} 行文字（可信度 ${Math.round(Number(data.confidence||0)*100)}%），发送问题时会一并检索。`;if(!$("question").value.trim())$("question").value=data.suggested_question}catch(error){state.image=null;$("imageStatus").textContent=`图片识别失败：${error.message}`}}
async function saveFeedback(rating,data,question,row){const box=row.querySelector(".feedback");const comment=rating==="down"?(prompt("请填写需要纠正或补充的内容（选填）")||""):"";try{await getJson("/api/feedback",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({rating,comment,message_id:data.message_id,conversation_id:data.conversation_id,question,answer:data.answer,vehicle_series:$("vehicleSeries").value,scene:$("scene").value})});box.textContent="评价与意见已记录"}catch(error){box.textContent=error.message}}

async function loadCapabilities(){try{const data=await getJson("/api/intents");if(data.intents?.length)state.intents=data.intents}catch{}$("capabilityList").innerHTML=state.intents.map(item=>`<button type="button" data-intent="${esc(item.id)}" class="${state.intent===item.id?"active":""}">${esc(item.name)}</button>`).join("");$("capabilityList").querySelectorAll("button").forEach(button=>button.addEventListener("click",()=>{state.intent=button.dataset.intent;$("capabilityList").querySelectorAll("button").forEach(item=>item.classList.toggle("active",item===button));const intent=state.intents.find(item=>item.id===state.intent);if(intent?.scene)$("scene").value=intent.scene;else if(["all","vin"].includes(intent?.id))$("scene").value="";$("question").placeholder=intent?.example_question||"请输入车辆问题"}))}
async function loadHistory(){try{const data=await getJson("/api/history?limit=6");$("historySection").hidden=!data.history?.length;$("historyList").innerHTML=(data.history||[]).map(item=>`<button type="button" data-id="${esc(item.id)}"><b>${esc(item.question||"未命名查询")}</b><small>${esc(item.vehicle_series||item.scene||"智能问答")}</small></button>`).join("");$("historyList").querySelectorAll("button").forEach(button=>button.addEventListener("click",async()=>{const detail=await getJson(`/api/history?conversation_id=${encodeURIComponent(button.dataset.id)}`);$("conversation").innerHTML="";(detail.messages||[]).forEach(item=>item.role==="user"?addUser(item.content):addAssistant({answer:item.content,sources:[],reference_materials:[]},""));state.conversationId=button.dataset.id}))}catch{}}

$("askForm").addEventListener("submit",event=>{event.preventDefault();const value=$("question").value.trim();if(value){$("question").value="";ask(value)}});
$("imageButton").addEventListener("click",()=>$("imageInput").click());
$("imageInput").addEventListener("change",event=>recognizeImage(event.target.files?.[0]));
$("answerMode").addEventListener("change",loadStatus);
document.querySelectorAll(".quick-grid button").forEach(button=>button.addEventListener("click",()=>ask(button.querySelector("span").textContent)));
$("clearButton").addEventListener("click",()=>{state.conversationId=null;state.last=null;state.image=null;state.diagnosticPrompt="";$("imageStatus").hidden=true;$("conversation").innerHTML='<article class="bubble-row assistant"><div class="avatar">智</div><div class="bubble">新对话已开始，请描述车辆问题。</div></article>';$("quickSection").hidden=false;scrollBottom()});
updateClock();setInterval(updateClock,30000);loadStatus();loadCapabilities();loadHistory();
